

POST http://web.chacuo.net/netrsakeypair
Accept: */*
accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
proxy-connection: keep-alive
x-requested-with: XMLHttpRequest
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/x-www-form-urlencoded

data=2048&type=rsakeypair&arg=t%3D1_o%3D0_p%3D


